os: osx
osx_image: xcode7.2
language: cpp
compiler: clang
env: CXX="`which clang++` -std=c++11 -stdlib=libc++" LINK="`which clang++` -std=c++11 -stdlib=libc++" GYP_DEFINES="clang=1 mac_deployment_target=10.7"

script:
- bash build.sh
- "ls $TRAVIS_BUILD_DIR && ls $TRAVIS_BUILD_DIR/dist"

deploy:
  provider: releases
  api_key:
    secure: ZgZqb7/n0JEja4Sr7sIQ2A5EjJz9YHuZX5SeG6ZkSFQc4vvk6yq9xXSEU3tUyXMJIzytclj5ZaumroobkVvjmx+UFOxxn58is654Z7aXLspLeVH61TV1Tkl5qVdnkKuQIhb+QstY3Tc3NTygEZYQJPHCZG0d6MimXYFJAj1A+5p+LANcW9ZEEDeeW0zmdwrAZWJP0506+lUtdd4IiKIkBurl9H//hZMn1wtT0uLN73OfAS1194fPkJl7rEGZJf+3fjLu2s8/6t0BfK7aXDeLoRI6sGxbgNO2xQV4RxJ1VyL9xrcTezzbfWMhkqZ4vQr4PKILa+1TO4+DlpDtrG9zACNlRXiXY5w5SY/uAd35bn6+L4U6PZcmCc9sqOd0Vqy3HZU4W/Tu/pcfMUEHzUqbjbf5XsnLtRlwa2bOKnxwj2y7gv0QGjC42kmvZnfpDdP+0fsDMVmb+nFqNOlLhPbZHtHUSMUR2n5Up1o6+lVrA8FCnv8NaOA3qVZ+GqNAtaTAScr5lNMeB6C7g7qno1F1OYV6FXTq3hJuwcEfj1aAmYqlLJCcUDfvpOmtR0afNpE/vT9FnBfyu+sWPllz5GVjwZZU5dB/dj98/LXvXWdoaBFFbtRNhTPaAhYfWFc0FeTQXQGMEhRHZnbC68tfH4p2pdCTj0xicJGk04UDGuIqSUQ=
  file_glob: true
  file: libv8*.tar.gz
  skip_cleanup: true
  on:
    tags: true