version: 1.0.{build}
build_script:
- ps: .\build.ps1
artifacts:
- path: libv8*.zip
  name: libv8
deploy:
- provider: GitHub
  tag: '%APPVEYOR_REPO_TAG_NAME%'
  auth_token:
    secure: TcTgvgqFgep3CawLJfghwhG4VwcZm6+c4GwCdLXg4zUFktqUEWQXkn4QQUG3WOxY
  artifact: libv8
  on:
    APPVEYOR_REPO_TAG: true